environment:
  D_VER: 2.080.0
install:
  - curl --location -o C:\dmd.7z http://downloads.dlang.org/releases/2.x/%D_VER%/dmd.%D_VER%.windows.7z
  - 7z x C:\dmd.7z -oC:\
  - set PATH=C:\dmd2\windows\bin;%PATH%
  - dmd.exe --version
build_script:
  - cd tests && rdmd runtests.d args c++ constructs coverage empty emptyset enum eol expression functplparam imports imports-only lines list noreduce noremove noremove2 noremovefile noremovespan obfuscate obfuscate-kl one pairs reduceonly words && git diff --exit-code
